### ISSUE TITLE
fix : Disabling a stage (or job) wipe the requirement list

### ISSUE THREAD

**Issue by skeetmtp** [ovh/cds#3873] opened 2019-01-21 16:02 UTC
Reporducing steps : 
* Add a requirement to a stage (ex bin:docker)
* Save
* Disable stage
* Save
* Enable Stage
* Save

Observe : 
* "requirements" list only contains bin:git

This is quite painful when you have a bunch of requirement and you want to do temporarily disable a stage

**Comment by fsamin** [comment] 2019-03-25 10:41
Since the last fixes on jobs, i'm unable to reproduce.
I'm closing this issue; feel free to reopen it.

**Comment by skeetmtp** [comment] 2019-04-02 13:30
still there, please see attached screen-cast :
![requirement_wipe](https://user-images.githubusercontent.com/2316424/55406340-340b0380-555c-11e9-85d6-1921027958d0.png)

**Closed** 2020-10-08 07:41 UTC
Labels: api, bug
